name: Deploy React to AWS EC2


# Triggers the workflow automatically on a push to the main branch. (Mandatory)
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

#This fetches the latest code from the GitHub repository. (Mandatory)
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

# Install Node.js and Dependencies
    - name: Install Node.js and dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: ''

    - run: npm install --no-lockfile
    - run: npm run build  # Build React project

#Securely copy files from GitHub to your EC2 instance.
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "*"    #All github files will deploy 
        target: "/var/myproject"

#Runs a remote SSH command to restart the server.
    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /var/myproject
          /home/ubuntu/.nvm/versions/node/v20.18.3/bin/pm2 restart Frontend || /home/ubuntu/.nvm/versions/node/v20.18.3/bin/pm2 start server.js --name Frontend
          

